import {test} from 'node:test';
import assert from 'node:assert/strict';
import {snapshotDigest, documentDigest} from '../scripts/lib/management-split-plan.js';
import {authSnapshotDigest, authSourceRecordDigest} from '../scripts/lib/management-auth-import-plan.js';
import {buildManagementAuthorizationPreview, managementAuthorizationPreviewDigest} from '../scripts/lib/management-authorization-preview.js';
const FA='sahmt-17a16',FB='sahmt-gestao-5ae66',time='2026-10-08T12:00:00Z';
const typed=v=>v===null?{nullValue:null}:typeof v==='boolean'?{booleanValue:v}:typeof v==='string'?{stringValue:v}:typeof v==='number'?{integerValue:String(v)}:Array.isArray(v)?{arrayValue:{values:v.map(typed)}}:{mapValue:{fields:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,typed(x)]))}};
const doc=(path,data)=>({path,fields:Object.fromEntries(Object.entries(data).map(([k,v])=>[k,typed(v)])),createTime:time,updateTime:time});
const auth=(uid,provider=true)=>({uid,email:uid+'@example.invalid',emailVerified:provider,disabled:false,providerData:provider?[{providerId:'google.com',uid:'google-'+uid,email:uid+'@example.invalid'}]:[]});
function fixture(){
 const profiles=[doc('users/admin',{uid:'admin',role:'administrador_app',active:true,access:true,permissions:{managementRead:true,trainingsManage:true}}),doc('users/denied',{uid:'denied',role:'usuario',active:true,access:false,permissions:{managementRead:true}}),doc('users/unlinked',{uid:'unlinked',role:'usuario',active:true,access:true,permissions:{managementRead:true}})];
 const documents=[...profiles,doc('managementAreas/area-a',{id:'area-a',active:true,version:1,managerUids:['admin','denied'],memberUids:['unlinked'],permissions:{}}),doc('documents/legacy',{managementAreaId:'area-a',active:true,version:1,createdByUid:'admin'}),doc('scopedDocuments/scoped',{managementAreaId:'area-a',active:true,version:1,audienceGroup:'RESTRICTED',createdByUid:'admin'}),
 ...['admin','denied','unlinked'].map(uid=>doc('documentAccessEmails/'+uid+'@example.invalid',{id:uid+'@example.invalid',email:uid+'@example.invalid',groups:['GENERAL','RESTRICTED'],active:true,version:1,createdByUid:'admin',updatedByUid:'admin',createdAt:time,updatedAt:time})),
 doc('evaluationFormConfigs/eval-a',{managerAreaId:'area-a',version:1,status:'READY',eligibleGroups:['GENERAL'],eligibleUids:[],publishedAudienceHash:'a'.repeat(64),accessVerifiedAt:time}),doc('evaluationActivities/eval-a',{managerAreaId:'area-a',version:1,status:'READY',eligibleGroups:['GENERAL'],eligibleUids:[],publishedAudienceHash:'a'.repeat(64),accessVerifiedAt:time}),doc('appConfig/features',{features:{management:true,trainings:false}})];
 const roots=['users','managementAreas','documentAccessEmails','documents','scopedDocuments','evaluationFormConfigs','evaluationActivities','appConfig','roles'];
 const sourceSnapshot={schemaVersion:1,projectId:FA,databaseId:'(default)',readTime:time,coverage:{complete:true,consistent:true,rootCollections:roots},documents};
 const destinationSnapshot={...structuredClone(sourceSnapshot),projectId:FB,coverage:{complete:true,consistent:true,rootCollections:[...roots,'migrationOrigins']},documents:[]};
 const sourceAuth={schemaVersion:1,projectId:FA,readTime:time,coverage:{complete:true,atomicSnapshot:false},users:[auth('admin'),auth('denied'),auth('unlinked',false)]};
 const manifest={schemaVersion:1,sourceProjectId:FA,destinationProjectId:FB,sourceDatabaseId:'(default)',destinationDatabaseId:'(default)',backupSha256:snapshotDigest(sourceSnapshot),identityMappings:sourceAuth.users.map(u=>({memberId:'member-'+u.uid,faUid:u.uid,fbUid:u.uid})),entries:documents.map(row=>({path:row.path,action:['users','documentAccessEmails','appConfig'].includes(row.path.split('/')[0])?'KEEP_FA':'COPY',reason:'Fictício somente local',scope:'GESTAO',evidence:'RELATION_VERIFIED',sourceSha256:documentDigest(row),dependencies:[]}))};
 const policy={schemaVersion:1,version:'preview-v1',sourceProjectId:FA,destinationProjectId:FB,mode:'OFFLINE_PROPOSAL_ONLY',managementSurfaceEnabled:false,performanceSurfaceEnabled:false,futureManagementGate:'DENIED',baseline:'FA_APP_MANAGEMENT_ADMIN_ONLY',cancelledTrainingRemainsStopped:true};
 const input={sourceSnapshot,destinationSnapshot,sourceAuth,manifest,policy,aclBindings:[],pins:{}};proofs(input);repin(input);return input;
}
function proofs(input){input.aclBindings=input.sourceAuth.users.filter(u=>u.providerData.length===1&&u.providerData[0].providerId==='google.com'&&u.emailVerified).map(u=>{const row=input.sourceSnapshot.documents.find(d=>d.path==='documentAccessEmails/'+u.email.toLowerCase());return {schemaVersion:1,path:row.path,sourceDocumentSha256:documentDigest(row),faUid:u.uid,googleUid:u.providerData[0].uid,authRecordSha256:authSourceRecordDigest(u),classification:'CAPTURED_INTENT_ONLY'};});}
function repin(input){input.manifest.backupSha256=snapshotDigest(input.sourceSnapshot);for(const entry of input.manifest.entries){const d=input.sourceSnapshot.documents.find(d=>d.path===entry.path);if(d)entry.sourceSha256=documentDigest(d);}input.pins={sourceSnapshotSha256:snapshotDigest(input.sourceSnapshot),destinationSnapshotSha256:snapshotDigest(input.destinationSnapshot),sourceAuthSha256:authSnapshotDigest(input.sourceAuth),manifestSha256:snapshotDigest(input.manifest),identityMappingsSha256:snapshotDigest(input.manifest.identityMappings),policySha256:snapshotDigest(input.policy),aclBindingsSha256:snapshotDigest(input.aclBindings)};}
const row=(input,path)=>input.sourceSnapshot.documents.find(d=>d.path===path);
const data=(input,path,key,value)=>{row(input,path).fields[key]=typed(value);};
function changed(change){const input=fixture();change(input);repin(input);return input;}
const expect=(change,pattern)=>assert.throws(()=>buildManagementAuthorizationPreview(changed(change)),pattern);

test('prévia determinística e isolada mantém zero concessões inclusive para administrador Google',()=>{
 const input=fixture(),before=structuredClone(input),p=buildManagementAuthorizationPreview(input);
 assert.deepEqual(input,before);assert.deepEqual(buildManagementAuthorizationPreview(input),p);assert.equal(p.resultSha256,managementAuthorizationPreviewDigest(p));
 assert.equal(p.productionAuthorized,false);assert.equal(p.authorizationReady,false);assert.equal(p.writeEnabled,false);assert.deepEqual(p.surfaces,{management:false,performance:false});
 for(const key of ['grants','leases','runtimeContexts','authImportRecords'])assert.deepEqual(p[key],[]);
 assert.equal(p.counts.effectivePermissions+p.counts.effectiveMemberships+p.counts.effectiveAclGrants+p.counts.authorizedFbContexts,0);
 assert.deepEqual(p.effects,{firestoreReadsIssued:0,firestoreWritesIssued:0,authChangesIssued:0,triggersActivated:0});
 assert.equal(p.counts.profiles,3);assert.equal(p.counts.aclProofBindings,2);assert.equal(p.counts.unresolvedAclIntents,1);
 assert.ok(p.proposals.identityCandidates.every(x=>x.active===false&&x.access===false&&x.loginAuthorized===false&&x.accountCreationProposed===false));
 assert.ok(p.proposals.aclIntents.every(x=>x.grantEffective===false&&x.active===false&&x.access===false));
});
test('membro estável provém só do mapa e dados observados ficam separados de propostas',()=>{
 const p=buildManagementAuthorizationPreview(fixture());assert.equal(p.proposals.identityCandidates.find(x=>x.faUid==='admin').proposedMemberId,'member-admin');
 assert.equal(p.sourceEvidence.profiles.find(x=>x.faUid==='admin').permissions.managementRead,true);assert.equal(p.counts.capturedAdminPredicates,1);
 assert.equal(p.sourceEvidence.profiles.every(x=>x.profileMemberIdPresent===false&&x.profileVersion===null),true);
 assert.ok(p.blockers.some(x=>x.code==='PROFILE_AUTHORIZATION_VERSION_UNAVAILABLE'));
});
test('DEFER mantém identidade proposta sem conta, contexto ou permissão FB',()=>{const p=buildManagementAuthorizationPreview(fixture());const u=p.proposals.identityCandidates.find(x=>x.faUid==='unlinked');assert.equal(u.sourceAuthClassification,'DEFER_UNLINKED_SOURCE_CAPTURE_ONLY');assert.equal(u.loginAuthorized,false);assert.equal(p.counts.authImports,0);assert.equal(p.counts.authorizedFbContexts,0);});
test('membership negada é evidência preservada sem relação efetiva',()=>{const p=buildManagementAuthorizationPreview(fixture());assert.equal(p.counts.memberships,3);assert.equal(p.counts.deniedMembershipEvidence,2);assert.ok(p.proposals.membershipCandidates.find(x=>x.faUid==='denied').sourceDenials.includes('SOURCE_PROFILE_INACTIVE_OR_NO_ACCESS'));assert.ok(p.proposals.membershipCandidates.find(x=>x.faUid==='unlinked').sourceDenials.includes('SOURCE_GOOGLE_IDENTITY_NOT_CONFIRMED'));assert.ok(p.proposals.membershipCandidates.every(x=>!x.membershipEffective&&!x.createsPermission));assert.equal(p.counts.boundAclDeniedByProfile,1);});
test('admin-only futuro nunca permite superfície por manager/grupo/trainingsManage',()=>{const input=changed(i=>i.policy.futureManagementGate='ADMINISTRATOR_ONLY');const p=buildManagementAuthorizationPreview(input);assert.deepEqual(p.surfaces,{management:false,performance:false});assert.deepEqual(p.grants,[]);assert.equal(p.counts.effectivePermissions,0);});
for(const field of ['managementSurfaceEnabled','performanceSurfaceEnabled'])test('nega superfície true '+field,()=>expect(i=>i.policy[field]=true,/SURFACE_POLICY_INVALID/));
for(const gate of ['MEMBERSHIPS_OR_GROUPS','ANY_PERMISSION','TRAININGS_MANAGE'])test('nega política ampliadora '+gate,()=>expect(i=>i.policy.futureManagementGate=gate,/SURFACE_POLICY_INVALID/));
test('nega cancelamento de treinamento alterado e política sem pin',()=>{expect(i=>i.policy.cancelledTrainingRemainsStopped=false,/SURFACE_POLICY_INVALID/);const i=fixture();delete i.pins.policySha256;assert.throws(()=>buildManagementAuthorizationPreview(i),/INPUT_PIN_MISMATCH/);});
for(const key of ['sourceSnapshotSha256','destinationSnapshotSha256','sourceAuthSha256','manifestSha256','identityMappingsSha256','policySha256','aclBindingsSha256'])test('nega pin divergente '+key,()=>{const i=fixture();i.pins[key]='0'.repeat(64);assert.throws(()=>buildManagementAuthorizationPreview(i),/INPUT_PIN_MISMATCH/);});
test('nega fonte incompleta/inconsistente e coleção obrigatória ausente',()=>{expect(i=>i.sourceSnapshot.coverage.complete=false,/INCOMPLETE_SNAPSHOT/);expect(i=>i.sourceSnapshot.coverage.consistent=false,/INCOMPLETE_SNAPSHOT/);expect(i=>i.sourceSnapshot.coverage.rootCollections=i.sourceSnapshot.coverage.rootCollections.filter(x=>x!=='scopedDocuments'),/DOCUMENT_OUTSIDE_COVERAGE|COVERAGE_MISSING/);expect(i=>{i.sourceSnapshot.documents=i.sourceSnapshot.documents.filter(d=>!d.path.startsWith('scopedDocuments/'));i.manifest.entries=i.manifest.entries.filter(d=>!d.path.startsWith('scopedDocuments/'));i.sourceSnapshot.coverage.rootCollections=i.sourceSnapshot.coverage.rootCollections.filter(x=>x!=='scopedDocuments');},/COVERAGE_MISSING/);});
test('cobertura notificationGroups ausente é bloqueio explícito de escopo',()=>{const p=buildManagementAuthorizationPreview(fixture());assert.ok(p.blockers.some(x=>x.code==='NOTIFICATION_GROUP_SCOPE_NOT_CAPTURED'));});
test('nega Auth incompleto e datas impossíveis',()=>{expect(i=>i.sourceAuth.coverage.complete=false,/AUTH_SNAPSHOT_INCOMPLETE/);expect(i=>i.sourceAuth.readTime='2026-02-30T12:00:00Z',/INVALID_SNAPSHOT_HEADER/);});
test('nega membro fonte contraditório e UID extra desconhecido',()=>{expect(i=>data(i,'users/admin','memberId','outro'),/PROFILE_MEMBER_CONFLICT/);expect(i=>i.manifest.identityMappings.push({memberId:'unknown-member',faUid:'unknown',fbUid:'unknown'}),/MAPPING_INVALID|INVALID_IDENTITY_MAPPING/);});
test('nega mapa duplicado, UID remapeado e colisão de membro',()=>{expect(i=>i.manifest.identityMappings.push({...i.manifest.identityMappings[0]}),/MAPPING_COLLISION|MAPPING_INVALID/);expect(i=>i.manifest.identityMappings[0].fbUid='other',/REMAP|MAPPING_INVALID/);expect(i=>i.manifest.identityMappings[1].memberId=i.manifest.identityMappings[0].memberId,/MAPPING_COLLISION/);});
test('nega permissão tipada falsa ou desconhecida',()=>{expect(i=>data(i,'users/admin','permissions',{managementRead:'true'}),/PERMISSION_INVALID/);expect(i=>data(i,'users/admin','permissions',{invented:true}),/PERMISSION_INVALID/);});
test('nega versão zero/double e perfil versionado errado',()=>{expect(i=>data(i,'managementAreas/area-a','version',0),/AREA_INVALID/);expect(i=>row(i,'managementAreas/area-a').fields.version={doubleValue:1},/AREA_INVALID/);expect(i=>data(i,'users/admin','version',0),/PROFILE_VERSION_INVALID/);});
test('nega gestor desconhecido e lista duplicada',()=>{expect(i=>data(i,'managementAreas/area-a','managerUids',['unknown']),/UID_NOT_MAPPED|AREA_MANAGER_INVALID/);expect(i=>data(i,'managementAreas/area-a','managerUids',['admin','admin']),/AREA_MANAGER_INVALID/);});
test('nega UID Auth e subject Google duplicados',()=>{expect(i=>i.sourceAuth.users.push({...i.sourceAuth.users[0]}),/AUTH_USER_INVALID/);expect(i=>i.sourceAuth.users[1].providerData[0].uid=i.sourceAuth.users[0].providerData[0].uid,/GOOGLE_UID_COLLISION/);});
test('nega status/provedor/materiais extra Auth malformados',()=>{expect(i=>i.sourceAuth.users[0].disabled='false',/AUTH_USER_INVALID/);expect(i=>i.sourceAuth.users[0].providerData.push({...i.sourceAuth.users[0].providerData[0]}),/PROVIDER_AMBIGUOUS/);expect(i=>i.sourceAuth.users[0].passwordHash='sensitive-test-fixture',/UNEXPECTED_FIELD/);});
test('ACL sem prova continua intenção sem UID, grupos efetivos ou grant',()=>{const p=buildManagementAuthorizationPreview(changed(i=>i.aclBindings=[]));assert.equal(p.counts.unresolvedAclIntents,3);assert.ok(p.proposals.aclIntents.every(x=>x.binding===null&&!x.grantEffective));});
test('e-mail do perfil não é identidade nem prova ACL',()=>{const input=changed(i=>data(i,'users/unlinked','email','admin@example.invalid'));const p=buildManagementAuthorizationPreview(input);assert.equal(p.proposals.aclIntents.filter(x=>x.binding?.faUid==='admin').length,1);assert.ok(p.proposals.identityCandidates.some(x=>x.faUid==='unlinked'&&x.proposedMemberId==='member-unlinked'));});
for(const key of ['faUid','googleUid','sourceDocumentSha256','authRecordSha256'])test('nega prova ACL alterada '+key,()=>expect(i=>i.aclBindings[0][key]=key.endsWith('Sha256')?'0'.repeat(64):'unknown',/ACL_BINDING_INVALID|ACL_BINDING_PROOF_MISMATCH/));
test('nega ACL prova repetida e criação de binding para DEFER',()=>{expect(i=>i.aclBindings.push({...i.aclBindings[0]}),/ACL_BINDING_INVALID/);expect(i=>{const u=i.sourceAuth.users[2],a=row(i,'documentAccessEmails/unlinked@example.invalid');i.aclBindings.push({schemaVersion:1,path:a.path,sourceDocumentSha256:documentDigest(a),faUid:u.uid,googleUid:'invented',authRecordSha256:authSourceRecordDigest(u),classification:'CAPTURED_INTENT_ONLY'});},/ACL_BINDING_PROOF_MISMATCH/);});
test('nega intenção ACL ambígua por e-mail Auth compartilhado',()=>expect(i=>{i.sourceAuth.users[1].email='admin@example.invalid';i.sourceAuth.users[1].providerData[0].email='admin@example.invalid';},/ACL_EMAIL_AMBIGUOUS/));
test('nega divergência e-mail Auth/Google na prova, mesmo com perfil compatível',()=>expect(i=>{i.sourceAuth.users[0].providerData[0].email='other@example.invalid';i.aclBindings[0].authRecordSha256=authSourceRecordDigest(i.sourceAuth.users[0]);},/ACL_BINDING_PROOF_MISMATCH/));
test('nega ACL inválida/versionamento/grupos/atores',()=>{expect(i=>data(i,'documentAccessEmails/admin@example.invalid','version',0),/ACL_SCHEMA_INVALID/);expect(i=>data(i,'documentAccessEmails/admin@example.invalid','groups',['RESTRICTED','RESTRICTED']),/ACL_GROUP_INVALID/);expect(i=>data(i,'documentAccessEmails/admin@example.invalid','groups',[]),/ACL_ACTIVE_EMPTY/);expect(i=>data(i,'documentAccessEmails/admin@example.invalid','createdByUid','unknown'),/ACL_ACTOR_UNMAPPED/);});
test('documento legado não ganha GENERAL e autoria não vira identidade',()=>{const p=buildManagementAuthorizationPreview(fixture());const legacy=p.proposals.contentCandidates.find(x=>x.collection==='documents');assert.deepEqual(legacy.intendedGroups,[]);assert.equal(legacy.classification,'LEGACY_AUDIENCE_UNSPECIFIED');assert.equal(p.proposals.identityCandidates.length,3);});
test('nega público inválido ou área desconhecida',()=>{expect(i=>data(i,'scopedDocuments/scoped','audienceGroup','PUBLIC'),/CONTENT_AUDIENCE_INVALID/);expect(i=>data(i,'scopedDocuments/scoped','managementAreaId','unknown'),/STRING_RELATION_NEEDS_BACKUP_OR_PROJECTION|SPLIT_PLAN_BLOCKED|CONTENT_INVALID/);});
test('configuração pendente permanece sem runtime mesmo com marcador histórico',()=>{const p=buildManagementAuthorizationPreview(changed(i=>{data(i,'evaluationFormConfigs/eval-a','status','CONFIGURATION_PENDING');data(i,'evaluationActivities/eval-a','status','CONFIGURATION_PENDING');}));assert.equal(p.counts.evaluationStatuses.CONFIGURATION_PENDING,1);assert.ok(p.blockers.some(x=>x.code==='EVALUATION_CONFIGURATION_NOT_READY'));assert.ok(p.proposals.evaluationCandidates.every(x=>!x.runtimeActivation&&!x.triggerActivation&&!x.accessEffective));});
test('nega par ausente, grupos divergentes, UID desconhecido e hash divergente',()=>{expect(i=>{i.sourceSnapshot.documents=i.sourceSnapshot.documents.filter(d=>d.path!=='evaluationActivities/eval-a');i.manifest.entries=i.manifest.entries.filter(d=>d.path!=='evaluationActivities/eval-a');},/PAIR_MISSING/);expect(i=>data(i,'evaluationActivities/eval-a','eligibleGroups',['RESTRICTED']),/ELIGIBILITY_CONFLICT/);expect(i=>data(i,'evaluationFormConfigs/eval-a','eligibleUids',['unknown']),/UID_NOT_MAPPED|EVALUATION_UID_INVALID/);expect(i=>data(i,'evaluationActivities/eval-a','publishedAudienceHash','b'.repeat(64)),/AUDIENCE_HASH_INVALID/);});
test('flags appConfig são evidência e não ligam proposta',()=>{const p=buildManagementAuthorizationPreview(fixture());assert.deepEqual(p.sourceEvidence.appFeatureFlags[0].knownSurfaceFlags,[{field:'features.management',state:true},{field:'features.trainings',state:false}]);assert.deepEqual(p.surfaces,{management:false,performance:false});});
test('proposta não inclui e-mail, nome, respostas ou payloads Auth originais',()=>{const p=buildManagementAuthorizationPreview(fixture());assert.equal(JSON.stringify(p).includes('@example.invalid'),false);assert.equal(JSON.stringify(p).includes('providerData'),false);assert.equal(JSON.stringify(p).includes('publishedAudienceHash'),true);});
test('resultado/hash/retorno independentes de mutação do chamador',()=>{const input=fixture(),p=buildManagementAuthorizationPreview(input);input.policy.version='changed';input.sourceAuth.users[0].uid='changed';assert.equal(p.policy.version,'preview-v1');assert.equal(p.resultSha256,managementAuthorizationPreviewDigest(p));p.surfaces.management=true;assert.notEqual(p.resultSha256,managementAuthorizationPreviewDigest(p));});
test('nega accessor/hidden/prototype/ciclo/array esparso antes de hashear',()=>{for(const mutate of [i=>Object.defineProperty(i.policy,'version',{enumerable:true,get(){throw Error('must-not-run');}}),i=>Object.defineProperty(i.policy,'hidden',{value:true}),i=>Object.setPrototypeOf(i.policy,{extra:true}),i=>i.policy.loop=i.policy,i=>i.aclBindings=new Array(2)]){const i=fixture();mutate(i);assert.throws(()=>buildManagementAuthorizationPreview(i),/JSON_|NOT_PLAIN|INPUT_CYCLE/);}});
test('classificação KEEP_FA nunca pede candidato de destino para conteúdo retido',()=>{const p=buildManagementAuthorizationPreview(changed(i=>i.manifest.entries.find(e=>e.path==='documents/legacy').action='KEEP_FA'));const d=p.proposals.contentCandidates.find(c=>c.collection==='documents');assert.equal(d.sourceClassificationAction,'KEEP_FA');assert.equal(d.destinationCandidateRequestedByManifest,false);assert.equal(d.accessEffective,false);});
test('contagens de status constructor e __proto__ não usam propriedades herdadas',()=>{for(const status of ['constructor','__proto__']){const p=buildManagementAuthorizationPreview(changed(i=>{data(i,'evaluationFormConfigs/eval-a','status',status);data(i,'evaluationActivities/eval-a','status',status);}));assert.equal(Object.hasOwn(p.counts.evaluationStatuses,status),true);assert.equal(p.counts.evaluationStatuses[status],1);assert.ok(p.blockers.some(b=>b.code==='EVALUATION_CONFIGURATION_NOT_READY'));}});
