import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {evaluationPresentation, evaluationAwardGroups, createEvaluationLifecycle, evaluationSessionCanPreserve, evaluationFailureState, evaluationCalendarInput, evaluationConfigurationFields, evaluationPendingParticipations} from '../src/performance-ui.js';

const state = (performanceTotal = 4, maxPerformance = 8) => ({summary:{uid:'person-a',status:'CONFIRMED',performanceTotal,governanceTotal:7,performanceRevision:3,governanceRevision:9},reference:{performanceStatus:'CONFIRMED',governanceStatus:'CONFIRMED',performanceRevision:3,governanceRevision:9,maxPerformance,eligibleCount:2,allZero:false},fromCache:false,pendingWrites:false});
const performance = snapshot => evaluationPresentation(snapshot,{subjectUid:'person-a',category:'PERFORMANCE'});
const tick = () => new Promise(resolve => setImmediate(resolve));

test('performance percentage uses only confirmed performance and one decimal',()=>{const result=performance(state());assert.equal(result.total,4);assert.equal(result.percentage,50);assert.equal(result.percentageLabel,'50,0%');});
test('governance changes cannot change performance or its reference percentage',()=>{const first=state(),second=structuredClone(first);second.summary.governanceTotal=-99;second.summary.governanceRevision++;second.reference.governanceRevision++;assert.deepEqual(performance(second),performance(first));});
test('negative confirmed performance is preserved',()=>{const result=performance(state(-2,8));assert.equal(result.total,-2);assert.equal(result.percentage,-25);assert.equal(result.percentageLabel,'-25,0%');});
test('all zero shows zero percent only with consistent confirmed reference',()=>{const input=state(0,0);input.reference.allZero=true;assert.equal(performance(input).percentageLabel,'0,0%');});
test('nonpositive reference preserves negative balance without invented percent',()=>{const result=performance(state(-2,-1));assert.equal(result.total,-2);assert.equal(result.percentage,null);assert.equal(result.percentageLabel,'Sem referência positiva');});
test('missing summary is awaiting, never zero',()=>{const input=state();input.summary=null;assert.equal(performance(input).total,null);assert.equal(performance(input).confirmed,false);});
test('mismatched summary/reference revision cannot be presented confirmed',()=>{const input=state();input.reference.performanceRevision++;assert.equal(performance(input).confirmed,false);assert.equal(performance(input).total,null);});
test('private summary from another account is discarded',()=>{const input=state();input.summary.uid='person-b';assert.equal(performance(input).confirmed,false);});
for(const flag of ['fromCache','pendingWrites'])test(`${flag} does not pretend current server confirmation`,()=>{const input=state();input[flag]=true;assert.equal(performance(input).confirmed,false);assert.equal(performance(input).total,null);});
test('offline reference is explicitly unavailable',()=>{const result=evaluationPresentation(state(),{subjectUid:'person-a',category:'PERFORMANCE',online:false});assert.equal(result.state,'offline');assert.equal(result.total,null);});
test('governance has its own total and no comparison percentage',()=>{const result=evaluationPresentation(state(),{subjectUid:'person-a',category:'GOVERNANCE'});assert.equal(result.total,7);assert.equal(result.percentage,null);assert.equal(result.percentageLabel,'');});
test('award grouping keeps modalities, category, version, account and Checklist distinct',()=>{const rows=[{id:'a',uid:'person-a',category:'PERFORMANCE',activityId:'activity',version:'1',modality:'ACKNOWLEDGEMENT',points:1},{id:'b',uid:'person-a',category:'PERFORMANCE',activityId:'activity',version:'1',modality:'SUGGESTION',points:2},{id:'c',uid:'person-a',category:'GOVERNANCE',activityId:'activity',version:'1',modality:'MATERIAL',points:1},{id:'d',uid:'person-b',category:'PERFORMANCE',activityId:'activity',version:'1',modality:'TEST',points:100},{id:'e',uid:'person-a',category:'PERFORMANCE',activityId:'checklist-day',modality:'CHECKLIST_TRANSFER',transferId:'day',points:-1}];const result=evaluationAwardGroups(rows,{subjectUid:'person-a',category:'PERFORMANCE'});assert.equal(result.length,2);assert.equal(result.find(x=>!x.checklist).points,3);assert.equal(result.find(x=>x.checklist).points,-1);assert.deepEqual(result.find(x=>!x.checklist).modalities,{ACKNOWLEDGEMENT:1,SUGGESTION:2});});
test('ledger differences are not incorrectly used as current awards',()=>{const result=evaluationAwardGroups([{id:'a',uid:'person-a',category:'PERFORMANCE',activityId:'a',modality:'TEST',points:0,originalPoints:10}],{subjectUid:'person-a',category:'PERFORMANCE'});assert.equal(result[0].points,0);});

test('lifecycle returns cleanup immediately and stops a late subscription',async()=>{let resolveServices,started=0;const services=new Promise(resolve=>{resolveServices=resolve;});const view=createEvaluationLifecycle({services,actorUid:'person-a',category:'PERFORMANCE'});view.dispose();resolveServices({watchEvaluation(){started++;return()=>{};}});await tick();assert.equal(started,0);assert.equal(view.snapshot().state,'closed');});
test('lifecycle ignores callbacks after account/permission change and cleans listener',async()=>{let callback,allowed=true,stopped=0;const updates=[];const view=createEvaluationLifecycle({services:{watchEvaluation({onData}){callback=onData;return()=>{stopped++;};}},actorUid:'person-a',category:'PERFORMANCE',isCurrent:()=>allowed,onData:data=>updates.push(data)});await tick();callback(state());assert.equal(updates.length,1);allowed=false;callback(state(100));assert.equal(updates.length,1);assert.equal(stopped,1);view.dispose();assert.equal(stopped,1);});
test('suspend and reconnect detach old listeners and retain only new callbacks',async()=>{const callbacks=[];let stops=0;const updates=[];const services={watchEvaluation({onData}){callbacks.push(onData);return()=>{stops++;};}};const view=createEvaluationLifecycle({services,actorUid:'person-a',category:'PERFORMANCE',onData:data=>updates.push(data)});await tick();view.suspend();callbacks[0](state());assert.equal(updates.length,0);assert.equal(stops,1);view.resume();await tick();callbacks[1](state());assert.equal(updates.length,1);view.setOnline(true);await tick();assert.equal(stops,2);callbacks[1](state(99));assert.equal(updates.length,1);callbacks[2](state());assert.equal(updates.length,2);view.dispose();assert.equal(stops,3);});
test('lifecycle binds authorized subject, category and explicit loaded limit',async()=>{let args;const view=createEvaluationLifecycle({services:{watchEvaluation(value){args=value;return()=>{};}},actorUid:'admin-a',subjectUid:'person-a',category:'GOVERNANCE',loadedLimit:400});await tick();assert.equal(args.actorUid,'admin-a');assert.equal(args.subjectUid,'person-a');assert.equal(args.category,'GOVERNANCE');assert.equal(args.loadedLimit,400);view.dispose();});
test('lifecycle exposes cache and pending state distinctly from confirmation',async()=>{let callback;const view=createEvaluationLifecycle({services:{watchEvaluation({onData}){callback=onData;return()=>{};}},actorUid:'person-a',category:'PERFORMANCE'});await tick();callback({...state(),fromCache:true});assert.equal(view.snapshot().confirmed,false);callback({...state(),pendingWrites:true});assert.equal(view.snapshot().state,'pending');callback(state());assert.equal(view.snapshot().confirmed,true);view.dispose();});
test('new training entry does not mount or query the legacy player',async()=>{const main=await readFile(new URL('../src/main.js',import.meta.url),'utf8');assert.match(main,/training: \['Desempenho'/);assert.match(main,/training-title">DESEMPENHO/);const branch=main.slice(main.indexOf("  if (route === 'training') {",main.indexOf('async function loadModule')),main.indexOf("  if (route === 'management' && hasFinanceOnly"));assert.match(branch,/mountPerformanceModule/);assert.doesNotMatch(branch,/listTrainingProgress|listTrainingCatalog|mountTrainingModule/);assert.match(main,/cleanupCurrentModule\?\.suspend\?\.\(\)/);assert.match(main,/cleanupCurrentModule\?\.resume\?\.\(\)/);});
test('request editors remain outside listener-updated containers',async()=>{const source=await readFile(new URL('../src/performance-ui.js',import.meta.url),'utf8');const renderer=source.slice(source.indexOf('function renderSnapshot('),source.indexOf('function blockAccess('));assert.doesNotMatch(renderer,/content\.innerHTML|page\.innerHTML|data-evaluation-form/);assert.match(source,/Autoaprovação bloqueada/);assert.match(source,/expectedAwardVersion/);assert.match(source,/correctedPoints, reason:/);assert.match(source,/transferência pareada do Checklist/);assert.match(source,/hasMore !== true/);});
test('same account and unrelated permission grants preserve evaluation drafts',()=>{const first={status:'signed-in',user:{uid:'person-a'},profile:{active:true,access:true,role:'anestesiologista',displayName:'Pessoa fictícia',sigla:'FA',permissions:{trainingsRead:true}}};const next=structuredClone(first);next.profile.permissions.notificationsRead=true;assert.equal(evaluationSessionCanPreserve(first,next),true);});
test('revocation, role escalation and account changes cannot preserve private evaluation',()=>{const first={status:'signed-in',user:{uid:'person-a'},profile:{active:true,access:true,role:'anestesiologista',permissions:{trainingsRead:true}}};for(const mutate of [s=>s.profile.access=false,s=>s.profile.permissions.trainingsRead=false,s=>s.user.uid='person-b',s=>s.profile.permissions.admin=true]){const next=structuredClone(first);mutate(next);assert.equal(evaluationSessionCanPreserve(first,next),false);}});
test('administrative request versions remain numeric and completed requests leave pending list',async()=>{const source=await readFile(new URL('../src/performance-ui.js',import.meta.url),'utf8');assert.match(source,/const version = Number\(values.version\)/);assert.match(source,/const previousVersion = Number\(values.previousVersion\), newVersion = Number\(values.newVersion\)/);assert.match(source,/Number.isSafeInteger\(newVersion\)/);assert.match(source,/'COMPLETED', 'PROCESSED'/);assert.doesNotMatch(source,/version: values.version.trim\(\)|newVersion: values.newVersion.trim\(\)/);});
test('list rendering keeps keyed history, drafts and scroll through reconciliation',async()=>{const source=await readFile(new URL('../src/performance-ui.js',import.meta.url),'utf8');assert.match(source,/reconcileReportMarkup\(element, value/);assert.match(source,/details\[open\]/);assert.match(source,/form\[data-dirty/);});
test('form copies of the same canonical credit scope remain one activity per version',()=>{const result=evaluationAwardGroups([{id:'a',uid:'person-a',category:'PERFORMANCE',creditScopeId:'matter',activityId:'form-one',version:1,modality:'ACKNOWLEDGEMENT',points:1},{id:'b',uid:'person-a',category:'PERFORMANCE',creditScopeId:'matter',activityId:'form-two',version:1,modality:'TEST',points:8}],{subjectUid:'person-a',category:'PERFORMANCE'});assert.equal(result.length,1);assert.equal(result[0].points,9);});

test('editor versions are captured at selection and cannot silently rebase after a concurrent update',async()=>{const source=await readFile(new URL('../src/performance-ui.js',import.meta.url),'utf8');assert.match(source,/form.dataset.expectedAwardVersion = String\(award.awardVersion\)/);assert.match(source,/award.awardVersion !== expectedAwardVersion/);assert.match(source,/form.dataset.expectedConfigVersion = String\(activity.configVersion/);assert.match(source,/expectedVersion !== Number\(activity.configVersion/);assert.match(source,/form.dataset.expectedAssignmentVersion = String\(assignment/);assert.match(source,/expectedVersion !== Number\(assignmentFor/);});

test('history limit is explicit and loading more keeps current records visible',async()=>{const source=await readFile(new URL('../src/performance-ui.js',import.meta.url),'utf8');assert.match(source,/openScope\(\{retain: true\}\)/);assert.match(source,/Math.min\(5000, loadedLimit \+ 200\)/);assert.match(source,/Histórico parcial: limite de 5.000 registros/);assert.match(source,/more.disabled = historyLimitReached/);});

test('Checklist activity labels use a Portuguese calendar date without internal document IDs',()=>{const result=evaluationAwardGroups([{id:'award',uid:'person-a',category:'PERFORMANCE',modality:'CHECKLIST',transferId:'checklist-2026-10-03',activityId:'checklist-2026-10-03',points:-1}],{subjectUid:'person-a',category:'PERFORMANCE'});assert.equal(result[0].title,'Checklist · 03/10/2026');});

test('summary arriving before its award updates cannot confirm a mismatched visible balance',()=>{const input=state(4);input.awards=[{uid:'person-a',category:'PERFORMANCE',points:3}];assert.equal(performance(input).confirmed,false);input.awards[0].points=4;assert.equal(performance(input).confirmed,true);});
test('award consistency ignores other subjects and categories while preserving decimal totals',()=>{const input=state(.3,1);input.awards=[{uid:'person-a',category:'PERFORMANCE',points:.1},{uid:'person-a',category:'PERFORMANCE',points:.2},{uid:'person-b',category:'PERFORMANCE',points:100},{uid:'person-a',category:'GOVERNANCE',points:100}];assert.equal(performance(input).confirmed,true);});
test('cosmetic profile edits preserve drafts while administration changes still invalidate them',()=>{const first={status:'signed-in',user:{uid:'person-a'},profile:{active:true,access:true,role:'anestesiologista',displayName:'Nome fictício inicial',sigla:'FA',permissions:{trainingsRead:true}}};const next=structuredClone(first);next.profile.displayName='Nome fictício atualizado';next.profile.sigla='FB';assert.equal(evaluationSessionCanPreserve(first,next),true);next.profile.role='administrador_app';assert.equal(evaluationSessionCanPreserve(first,next),false);});

test('idle preloading warms the evaluation UI instead of the legacy training player',async()=>{
  const vm=await import('node:vm'),source=await readFile(new URL('../src/main.js',import.meta.url),'utf8');
  const start=source.indexOf('function preloadOperationalDataWhenIdle('),end=source.indexOf('function escapeHtml(',start);assert.ok(start>=0&&end>start);
  const imports=[],context=vm.createContext({session:{status:'signed-in',user:{uid:'person-a'},profile:{role:'anestesiologista',permissions:{trainingsRead:true}},offline:false},navigator:{onLine:true},preloadedDataUsers:new Set(),scheduledDataPreloads:new Set(),startupBannerActive:true,window:{setTimeout:()=>{}},console,Promise,fakeImport:async name=>{imports.push(name);return {};}});
  const fn=source.slice(start,end).replaceAll('import.meta.env.PROD','false').replace(/import\((['"])([^'"]+)\1\)/g,'fakeImport("$2")');vm.runInContext(fn,context);context.preloadOperationalDataWhenIdle({uid:'person-a'});await tick();
  assert.ok(imports.includes('./performance-ui.js'));assert.equal(imports.includes('./training.js'),false);assert.deepEqual(imports,['./data.js','./performance-ui.js']);
  context.preloadOperationalDataWhenIdle({uid:'person-a'});await tick();assert.equal(imports.length,2);
});
test('offline network errors remain offline instead of pretending a fatal data failure',()=>{assert.equal(evaluationFailureState({code:'unavailable',message:'Failed to get document because client is offline'},{online:false}),'offline');assert.equal(evaluationFailureState({code:'firestore/unavailable'},{online:true}),'offline');});
test('permission and authentication revocations remain fatal even offline',()=>{for(const error of [{code:'permission-denied'},{code:'unauthenticated'},{message:'Seu acesso foi revogado.'}])assert.equal(evaluationFailureState(error,{online:false}),'blocked');});
test('reconnection replaces the failed network listener and restores confirmed server data',async()=>{let starts=0,stops=0,failed,live;const states=[],data=[];const view=createEvaluationLifecycle({actorUid:'person-a',category:'PERFORMANCE',services:{watchEvaluation(hooks){starts++;if(starts===1){failed=hooks;hooks.onError({code:'unavailable'});}else live=hooks;return()=>stops++;}},onState:state=>states.push(state),onData:payload=>data.push(payload)});await tick();assert.equal(stops,1);view.setOnline(true);await tick();assert.equal(starts,2);live.onData(state());assert.equal(view.snapshot().confirmed,true);assert.equal(data.length,1);failed.onData(state(99));assert.equal(data.length,1);view.dispose();assert.equal(stops,2);});
test('fatal revocation closes the listener and cannot reconnect when ownership is blocked',async()=>{let starts=0,stops=0,allowed=true,callback;const view=createEvaluationLifecycle({actorUid:'person-a',category:'PERFORMANCE',services:{watchEvaluation(hooks){starts++;callback=hooks;return()=>stops++;}},isCurrent:()=>allowed,onState:state=>{if(evaluationFailureState(state.error,{online:false})==='blocked')allowed=false;}});await tick();callback.onError({code:'permission-denied'});assert.equal(stops,1);view.setOnline(true);await tick();assert.equal(starts,1);view.dispose();});
test('metadata repaint cannot re-confirm an old cached payload after network failure',async()=>{const source=await readFile(new URL('../src/performance-ui.js',import.meta.url),'utf8');assert.match(source,/const liveConfirmed = lifecycle\?\.snapshot\(\).confirmed === true/);assert.match(source,/if \(live && liveConfirmed && snapshot.fromCache === false/);assert.match(source,/fromCache: snapshot.fromCache !== false \|\| !liveConfirmed/);assert.match(source,/onData: snapshot => renderSnapshot\(snapshot, \{live: true\}\)/);});

test('calendar editor restores Firestore timestamps using Sao Paulo dates, including end-of-day UTC rollover',()=>{
  assert.equal(evaluationCalendarInput({toDate:()=>new Date('2026-10-03T03:00:00.000Z')}),'2026-10-03');
  assert.equal(evaluationCalendarInput({seconds:Date.parse('2026-10-04T02:59:59.999Z')/1000}),'2026-10-03');
  assert.equal(evaluationCalendarInput(new Date('2026-10-04T02:59:59.999Z')),'2026-10-03');
  assert.equal(evaluationCalendarInput('2026-10-03'),'2026-10-03');
  for(const bad of [null,{},'2026-02-30','invalid',{seconds:NaN},{toDate:()=>{throw Error('invalid');}}]) assert.equal(evaluationCalendarInput(bad),'');
});
test('reopening an existing activity preserves custom acknowledgement, IDs, materials and exact configured manager area',()=>{
  const activity={id:'form-a',configVersion:3,version:2,creditScopeId:'matter',acknowledgementItemId:'ack-real',suggestionProblemItemId:'problem-real',suggestionProposalItemId:'proposal-real',suggestionBenefitItemId:'benefit-real',acknowledgementValue:'DECLARO CIÊNCIA',materialUrls:['https://drive.google.com/file/d/material-one/view','https://docs.google.com/document/d/material-two/edit'],validFrom:{toDate:()=>new Date('2026-10-03T03:00:00Z')},validUntil:{seconds:Date.parse('2026-11-01T02:59:59.999Z')/1000},eligibleUids:['person-a','manager-a'],managerAreaId:'assigned-area',areaIds:['secondary-area','assigned-area']};
  const fields=evaluationConfigurationFields(activity);assert.equal(fields.complete,true);
  assert.equal(fields.values.acknowledgementValue,'DECLARO CIÊNCIA');assert.equal(fields.values.acknowledgementItemId,'ack-real');assert.equal(fields.values.suggestionProblemItemId,'problem-real');assert.equal(fields.values.suggestionProposalItemId,'proposal-real');assert.equal(fields.values.suggestionBenefitItemId,'benefit-real');assert.equal(fields.values.materialUrls,activity.materialUrls.join('\n'));assert.equal(fields.values.validFrom,'2026-10-03');assert.equal(fields.values.validUntil,'2026-10-31');assert.equal(fields.values.managerAreaId,'assigned-area');assert.equal(fields.values.eligibleUids,'person-a\nmanager-a');
});
test('an older incomplete configured projection cannot silently clear materials or reset acknowledgement to SIM',async()=>{
  const fields=evaluationConfigurationFields({id:'form-a',configVersion:1,validFrom:'2026-10-03',validUntil:'2026-10-31'});assert.equal(fields.complete,false);assert.equal(fields.values.acknowledgementValue,'');
  const source=await readFile(new URL('../src/performance-ui.js',import.meta.url),'utf8');assert.match(source,/configurationComplete !== 'true'/);assert.match(source,/if \(!fields.complete\) return/);assert.match(source,/for \(const \[key, value\] of Object.entries\(fields.values\)\)/);
  const fresh=evaluationConfigurationFields({id:'new-form',configVersion:0});assert.equal(fresh.complete,true);assert.equal(fresh.values.acknowledgementValue,'SIM');
});

test('suggestion approval cannot hide a quiz grade that is still unavailable',()=>{
  const item={id:'participation',uid:'person-a',status:'APPROVED',suggestion:{status:'APPROVED'},test:{status:'PENDING_GRADE',score:null}};
  const snapshot={participations:[item,{...item,id:'other-account',uid:'person-b'}]};
  const pending=evaluationPendingParticipations(snapshot,'person-a');assert.equal(pending.length,1);assert.equal(pending[0].status,'PENDING');assert.equal(pending[0].test.status,'PENDING_GRADE');assert.equal(item.status,'APPROVED');
  item.test={status:'CONFIRMED',score:0};assert.deepEqual(evaluationPendingParticipations(snapshot,'person-a'),[]);
});
test('pending grade message follows the adapter PENDING_GRADE status without changing governance pending records',async()=>{
  const source=await readFile(new URL('../src/performance-ui.js',import.meta.url),'utf8');assert.match(source,/\['PENDING_GRADE', 'PENDING'\]\.includes\(item.test\?\.status\)/);assert.match(source,/category === 'PERFORMANCE' \? evaluationPendingParticipations/);
});
