const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '../src/report-dom.js'), 'utf8').replace('export function reconcileReportMarkup', 'function reconcileReportMarkup');
const context = vm.createContext({});vm.runInContext(source+'\nthis.reconcileReportMarkup=reconcileReportMarkup;',context);const reconcile=context.reconcileReportMarkup;
class Node {
  constructor(document, tag, text) {this.ownerDocument=document;this.nodeType=tag?1:3;this.tagName=tag?.toUpperCase();this.namespaceURI=tag?'html':null;this.nodeValue=text||null;this.childNodes=[];this.parentNode=null;this.attrs=new Map();this.scrollTop=0;this.scrollLeft=0;this.scrollHeight=0;this.clientHeight=0;this._value=undefined;this._checked=undefined;this.selectionStart=null;this.selectionEnd=null;this.selectionDirection='none';this.listeners=[];}
  get attributes(){return[...this.attrs].map(([name,value])=>({name,value}));}get id(){return this.getAttribute('id')||'';}get type(){return this.getAttribute('type')||'';}get parentElement(){return this.parentNode?.nodeType===1?this.parentNode:null;}get firstChild(){return this.childNodes[0]||null;}get nextSibling(){return this.parentNode?.childNodes[this.parentNode.childNodes.indexOf(this)+1]||null;}get isConnected(){return this===this.ownerDocument.body||Boolean(this.parentNode?.isConnected);}
  get value(){if(this._value!==undefined)return this._value;return this.tagName==='TEXTAREA'?this.textContent:this.getAttribute('value')||'';}set value(value){this._value=value;}get checked(){return this._checked??this.hasAttribute('checked');}set checked(value){this._checked=value;}
  get outerHTML(){if(this.nodeType!==1)return this.nodeValue;const attrs=[...this.attrs].map(([key,value])=>' '+key+'="'+String(value).replaceAll('"','&quot;')+'"').join('');const tag=this.tagName.toLowerCase();return '<'+tag+attrs+'>'+(['input','img','br','hr'].includes(tag)?'':this.childNodes.map(child=>child.outerHTML).join('')+'</'+tag+'>');}
  get textContent(){return this.nodeType===3?this.nodeValue:this.childNodes.map(x=>x.textContent).join('');}getAttribute(name){return this.attrs.has(name)?this.attrs.get(name):null;}hasAttribute(name){return this.attrs.has(name);}setAttribute(name,value){this.attrs.set(name,String(value));}removeAttribute(name){this.attrs.delete(name);}
  insertBefore(node,before){if(node===before)return node;if(node.parentNode)node.parentNode.removeChild(node);let index=before?this.childNodes.indexOf(before):this.childNodes.length;assert.ok(index>=0);this.childNodes.splice(index,0,node);node.parentNode=this;return node;}removeChild(node){const index=this.childNodes.indexOf(node);assert.ok(index>=0);this.childNodes.splice(index,1);node.parentNode=null;return node;}
  cloneNode(deep){const node=new Node(this.ownerDocument,this.tagName,this.nodeValue);node.attrs=new Map(this.attrs);if(deep)for(const child of this.childNodes)node.insertBefore(child.cloneNode(true),null);return node;}
  matches(selector){return selector.split(',').some(part=>{const s=part.trim();if(s.startsWith('#'))return this.id===s.slice(1);const a=s.match(/^\[([^=\]]+)(?:="([^"]*)")?\]$/);return a?this.hasAttribute(a[1])&&(a[2]===undefined||this.getAttribute(a[1])===a[2]):this.tagName===s.toUpperCase();});}
  querySelectorAll(selector){const result=[];for(const child of this.childNodes){if(child.nodeType===1&&child.matches(selector))result.push(child);result.push(...child.querySelectorAll(selector));}return result;}querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
  focus(){this.ownerDocument.activeElement=this;}setSelectionRange(start,end,direction){this.selectionStart=start;this.selectionEnd=end;this.selectionDirection=direction;}
  getBoundingClientRect(){if(this.rect)return this.rect;const top=(this.parentNode?.childNodes.indexOf(this)||0)*40-(this.parentNode?.scrollTop||0);return{top,bottom:top+40,left:0,right:200,width:200,height:40};}
}
class Document {
  constructor(){this.body=new Node(this,'body');this.activeElement=null;this.scrollingElement=this.body;this.defaultView={innerHeight:600};this.body.clientHeight=600;}
  createElement(tag){if(tag!=='template')return new Node(this,tag);const fragment=new Node(this);fragment.nodeType=11;return{content:fragment,set innerHTML(html){parse(html,fragment);}};}
}
function parse(html,parent){const stack=[parent];for(const token of html.match(/<[^>]+>|[^<]+/g)||[]){if(token.startsWith('</')){stack.pop();continue;}if(token.startsWith('<')){const name=token.match(/^<([\w-]+)/)?.[1];if(!name)continue;const node=new Node(parent.ownerDocument,name);for(const attr of token.matchAll(/([\w-]+)(?:="([^"]*)")?/g)){if(attr[1]!==name)node.setAttribute(attr[1],attr[2]??'');}stack.at(-1).insertBefore(node,null);if(!['input','br','hr','img'].includes(name)&&!token.endsWith('/>'))stack.push(node);}else stack.at(-1).insertBefore(new Node(parent.ownerDocument,null,token),null);}}
function setup(html){const document=new Document(),target=new Node(document,'section');document.body.insertBefore(target,null);parse(html,target);return{document,target,get:selector=>target.querySelector(selector)};}
function card(id,text,extra=''){return`<article data-event-record="${id}"><strong>${text}</strong>${extra}</article>`;}

test('identical markup performs no DOM mutations and retains node handlers',()=>{const h=setup(card('a','Old'));const node=h.get('[data-event-record="a"]');node.listeners.push('click');const stats=reconcile(h.target,card('a','Old'));assert.deepEqual({...stats},{inserted:0,removed:0,moved:0,updated:0});assert.equal(h.get('[data-event-record="a"]'),node);assert.deepEqual(node.listeners,['click']);});
test('inclusion, edit and exclusion use keyed nodes without duplicate records',()=>{const h=setup(card('a','Old')+card('b','Other'));const a=h.get('[data-event-record="a"]'),b=h.get('[data-event-record="b"]');reconcile(h.target,card('b','Updated')+card('c','New'));assert.equal(h.get('[data-event-record="b"]'),b);assert.equal(b.textContent,'Updated');assert.equal(a.parentNode,null);assert.equal(h.target.childNodes.length,2);assert.equal(h.target.firstChild,b);assert.equal(h.get('[data-event-record="c"]').textContent,'New');});
test('all stable report key attributes and IDs retain nodes through reorder',()=>{for(const key of['id','data-event-record','data-label-record','data-checklist-station','data-checklist-open-day']){const h=setup(`<div ${key}="a">A</div><div ${key}="b">B</div>`);const a=h.target.childNodes[0],b=h.target.childNodes[1];reconcile(h.target,`<div ${key}="b">B</div><div ${key}="a">A</div>`);assert.equal(h.target.childNodes[0],b);assert.equal(h.target.childNodes[1],a);}});
test('active input value, focus and selection survive new server attributes and reorder',()=>{const h=setup(card('a','A','<input id="editing" value="server">')+card('b','B'));const input=h.get('#editing');input.value='local draft';input.setSelectionRange(2,5,'forward');input.focus();reconcile(h.target,card('b','B')+card('a','Changed','<input id="editing" value="remote" required>'));assert.equal(h.get('#editing'),input);assert.equal(h.document.activeElement,input);assert.equal(input.value,'local draft');assert.equal(input.selectionStart,2);assert.equal(input.selectionEnd,5);assert.equal(input.selectionDirection,'forward');assert.equal(input.hasAttribute('required'),true);});
test('non-active fields follow server value and disabled attributes are not indiscriminately preserved',()=>{const h=setup('<input id="field" value="a"><button id="save">Save</button>');reconcile(h.target,'<input id="field" value="b" disabled><button id="save" disabled>Save</button>');assert.equal(h.get('#field').value,'b');assert.equal(h.get('#field').hasAttribute('disabled'),true);assert.equal(h.get('#save').hasAttribute('disabled'),true);});
test('active textarea and checked input state remain drafts, but removed active nodes stay removed',()=>{const h=setup('<textarea id="text">server</textarea><input id="check" type="checkbox">');const text=h.get('#text');text.value='draft';text.focus();reconcile(h.target,'<textarea id="text">remote</textarea><input id="check" type="checkbox" checked>');assert.equal(text.value,'draft');assert.equal(h.get('#check').checked,true);const check=h.get('#check');check.checked=false;check.focus();reconcile(h.target,'<textarea id="text">remote</textarea><input id="check" type="checkbox" checked>');assert.equal(check.checked,false);reconcile(h.target,'');assert.equal(text.isConnected,false);assert.equal(check.isConnected,false);});
test('runtime binding/loading attrs remain while report attributes update normally',()=>{const h=setup('<div id="history" data-history-bound="true" data-history-loading="true" data-history-loaded="true" data-custom-bound="yes" aria-expanded="false" hidden>Old</div>');reconcile(h.target,'<div id="history" aria-expanded="true">New</div>');const node=h.get('#history');for(const key of['data-history-bound','data-history-loading','data-history-loaded','data-custom-bound'])assert.equal(node.hasAttribute(key),true);assert.equal(node.hasAttribute('hidden'),false);assert.equal(node.getAttribute('aria-expanded'),'true');assert.equal(node.textContent,'New');});
test('explicit preservation retains loaded history and its toggle without preserving unrelated buttons',()=>{const h=setup('<button id="toggle" aria-expanded="true">Close</button><section id="history">Loaded history</section><button id="edit">Edit</button>');const history=h.get('#history'),toggle=h.get('#toggle');reconcile(h.target,'<button id="toggle" aria-expanded="false">Open</button><section id="history"></section><button id="edit" disabled>Edit</button>',{preserveSelectors:['#history','#toggle']});assert.equal(h.get('#history'),history);assert.equal(history.textContent,'Loaded history');assert.equal(toggle.getAttribute('aria-expanded'),'true');assert.equal(h.get('#edit').hasAttribute('disabled'),true);});
test('preserved child does not keep a deleted or unauthorized record in the report',()=>{const h=setup(card('a','A','<section id="history">Loaded</section>'));reconcile(h.target,'',{preserveSelectors:['#history']});assert.equal(h.target.childNodes.length,0);assert.equal(h.get('#history'),null);});
test('reused nodes preserve local scroll positions and ancestor scroll',()=>{const h=setup('<section id="inner">Text</section>');const inner=h.get('#inner');inner.scrollTop=35;inner.scrollLeft=4;h.target.scrollTop=25;h.target.scrollLeft=3;h.document.body.scrollTop=70;reconcile(h.target,'<section id="inner">Changed</section>');assert.equal(inner.scrollTop,35);assert.equal(inner.scrollLeft,4);assert.equal(h.target.scrollTop,25);assert.equal(h.target.scrollLeft,3);assert.equal(h.document.body.scrollTop,70);});
test('visible keyed reading anchor compensates for inserted records above it',()=>{const h=setup(card('a','A')+card('b','B'));h.target.clientHeight=100;h.target.scrollHeight=200;h.target.rect={top:0,bottom:100,left:0,right:200,width:200,height:100};h.target.scrollTop=40;const b=h.get('[data-event-record="b"]');const before=b.getBoundingClientRect().top;reconcile(h.target,card('new','New')+card('a','A')+card('b','B'));assert.equal(h.get('[data-event-record="b"]'),b);assert.equal(b.getBoundingClientRect().top,before);assert.equal(h.target.scrollTop,80);});
test('element kind changes replace the old node rather than reusing an incompatible key',()=>{const h=setup('<p id="same">Old</p>');const old=h.get('#same');reconcile(h.target,'<button id="same">New</button>');assert.notEqual(h.get('#same'),old);assert.equal(old.parentNode,null);assert.equal(h.get('#same').tagName,'BUTTON');});


test('unchanged keyed cards skip recursive work but retain runtime history and focus',()=>{const h=setup('');const html=card('a','A','<section id="history">Server placeholder</section><input id="draft" value="server">');reconcile(h.target,html);const node=h.get('[data-event-record="a"]'),history=h.get('#history'),draft=h.get('#draft');history.childNodes[0].nodeValue='Loaded runtime history';draft.value='Draft';draft.focus();let walked=0;const getAttributes=Object.getOwnPropertyDescriptor(Node.prototype,'attributes').get;Object.defineProperty(history,'attributes',{get(){walked++;return getAttributes.call(this);}});const stats=reconcile(h.target,html);assert.equal(walked,0);assert.equal(history.textContent,'Loaded runtime history');assert.equal(draft.value,'Draft');assert.equal(h.get('[data-event-record="a"]'),node);assert.deepEqual({...stats},{inserted:0,removed:0,moved:0,updated:0});});
test('changed keyed markup still updates authorization and index and then becomes a fast path',()=>{const h=setup('');reconcile(h.target,card('a','1','<button id="edit">Edit</button>'));const cardNode=h.get('[data-event-record="a"]');reconcile(h.target,card('new','1')+card('a','2','<button id="edit" disabled>Edit</button>'));assert.equal(h.get('[data-event-record="a"]'),cardNode);assert.equal(cardNode.firstChild.textContent,'2');assert.equal(h.get('#edit').hasAttribute('disabled'),true);const stats=reconcile(h.target,card('new','1')+card('a','2','<button id="edit" disabled>Edit</button>'));assert.deepEqual({...stats},{inserted:0,removed:0,moved:0,updated:0});});
test('cloned wrapper seeds keyed descendants for its first identical update',()=>{const h=setup('');const html='<ul>'+card('a','A','<section id="nested">Runtime</section>')+card('b','B')+'</ul>';reconcile(h.target,html);const nested=h.get('#nested');nested.childNodes[0].nodeValue='Loaded';reconcile(h.target,html);assert.equal(nested.textContent,'Loaded');});
